custom_envs:
  SimpleSokoban:
    env_type: sokoban
    max_actions_per_traj: 10 # used in environment state manager to control the actual max actions executed per trajectory
    env_instruction: "You are solving the Sokoban puzzle. You are the player and you need to push all boxes to targets. When you are right next to a box, you can push it by moving in the same direction. You cannot push a box through a wall, and you cannot pull a box. The answer should be a sequence of actions, like <answer>Right || Right || Up</answer>"
    max_tokens: 100 # used to curate llm prompt "max words", not used for rollout
    env_config: # keys should be a subset of SokobanConfig
      dim_x: 6
      dim_y: 6
      num_boxes: 1
      max_steps: 100

  LargerSokoban:
    env_type: sokoban
    max_actions_per_traj: 14
    env_instruction: "You are solving the Sokoban puzzle. You are the player and you need to push all boxes to targets. When you are right next to a box, you can push it by moving in the same direction. You cannot push a box through a wall, and you cannot pull a box. The answer should be a sequence of actions, like <answer>Right || Right || Up</answer>"
    max_tokens: 100
    env_config:
      dim_x: 10
      dim_y: 10
      num_boxes: 1
      max_steps: 100
      search_depth: 10

  ALFWorld:
    env_type: alfworld
    max_actions_per_traj: 30
    env_config: 
      config_path: "/projectnb/replearn/xfl/REIL/reil/env/alfworld/base_config.yaml"
      train_eval: "eval_out_of_distribution"
    